name: ppcfd
channels:
  - conda-forge
dependencies:
  - python=3.10
  - open3d
  - numpy=1.26.4
  - nccl
  - matplotlib
  - tqdm
  - pip
  - h5py
  - scipy
  - meshio
  - requests
  - einops
  - omegaconf
  - pynvml
  - xarray
  - xskillscore
